GET http://127.0.0.1:3000/

###
GET http://127.0.0.1:3000/posts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU5OTg0NTk1ODUwNywidXNlcm5hbWUiOiJqb24iLCJpYXQiOjE1OTk4NDU5NzJ9.ojwqgqm8SN7BR4UU36dJ1Bts6xxnqsHT2NHvMQjNtIE

###
GET http://127.0.0.1:3000/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU5OTg0NTk1ODUwNywidXNlcm5hbWUiOiJqb24iLCJpYXQiOjE1OTk4NDU5NzJ9.ojwqgqm8SN7BR4UU36dJ1Bts6xxnqsHT2NHvMQjNtIE

###
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
  "username": "jon",
  "password": "123456",
  "confirm-password": "123456"
}

###
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "username": "jon",
  "password": "123456"
}
